### ISSUE TITLE
Errors when using Pillow v10

### ISSUE THREAD

**Issue by philgyford** [philgyford/django-spectator#84]
We currently only use Pillow < v10. If we allow it we get several errors.

Some are due to the new constants in v10 ([see changelog](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html)) and [pilkit (used by django-imagekit) not yet being ready for that change](https://github.com/matthewwithanm/pilkit/issues/64).

Others are like:

```
======================================================================
FAIL: test_thumbnail (tests.events.test_models.EventTestCase)
By default it should use reading/publications/{pub.slug}/ as the path.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/phil/Projects/personal/django-spectator/.tox/py310-django42/lib/python3.10/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
  File "/Users/phil/Projects/personal/django-spectator/tests/events/test_models.py", line 385, in test_thumbnail
    self.assertEqual(
AssertionError: '/media/events/events/wpgz9/tester_coiJYER.jpg' != '/media/events/events/wpgz9/tester.jpg'
- /media/events/events/wpgz9/tester_coiJYER.jpg
?                                  --------
+ /media/events/events/wpgz9/tester.jpg


======================================================================
FAIL: test_thumbnail (tests.reading.test_models.PublicationTestCase)
By default it should use reading/publications/{pub.slug}/ as the path.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/phil/Projects/personal/django-spectator/.tox/py310-django42/lib/python3.10/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
  File "/Users/phil/Projects/personal/django-spectator/tests/reading/test_models.py", line 78, in test_thumbnail
    self.assertEqual(
AssertionError: '/media/reading/publications/wpgz9/tester_aOKwXGo.jpg' != '/media/reading/publications/wpgz9/tester.jpg'
- /media/reading/publications/wpgz9/tester_aOKwXGo.jpg
?                                         --------
+ /media/reading/publications/wpgz9/tester.jpg
```

(Tried using Python 3.10 and Django 4.1 and 4.2)

I haven't yet looked into whether that's related, or a different django-imagekit issue, or a Django thing.

**Comment by vstoykov** [comment]
I just released the new version of [pilkit](https://pypi.org/project/pilkit/3.0/) which is supporting Pillow 10. If you update your dependencies it will start working
